import assert from "node:assert/strict";
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,readdirSync,rmSync,symlinkSync,renameSync } from "node:fs";
import { tmpdir,hostname } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { cases,inputsFor } from "../../../../../evaluation/lifecycle/cases.mjs";
import { planLifecycle } from "../scripts/lib/lifecycle-journal.mjs";
import { packagePlugin } from "../package-plugin.mjs";
const api=await import("../scripts/lib/lifecycle-store.mjs").catch(()=>({}));
assert.equal(typeof api.runLifecycle,"function","durable guarded writes must exist");
const {runLifecycle,readLifecycle,publishRecord,withLifecycleLock}=api;
const temp=mkdtempSync(join(tmpdir(),"vibespec-journal-"));
const setup=name=>{
  const root=join(temp,name),input=inputsFor(cases[0]);mkdirSync(join(root,"initiatives"),{recursive:true});
  writeFileSync(join(root,"main.sot.json"),JSON.stringify(input.source));
  writeFileSync(join(root,"initiatives","batch.sot.json"),JSON.stringify(input.initiative));return root;
};
try {
  const root=setup("product"),start=readFileSync(join(root,"main.sot.json"),"utf8");
  runLifecycle(root,{kind:"init",reason:"Enroll"},{apply:false});
  assert.equal(existsSync(join(root,"history")),false,"dry-run cannot enroll or write");
  assert.equal(readLifecycle(root).report.status,"not-enrolled");
  runLifecycle(root,{kind:"init",reason:"Enroll"},{apply:true});
  assert.equal(readFileSync(join(root,"main.sot.json"),"utf8"),start,"enrollment preserves source bytes");
  const {records,docs}=readLifecycle(root);
  const planned=planLifecycle(records,docs,{kind:"merge",initiative:"batch",reason:"Land batch"});
  publishRecord(root,planned.record);
  assert.throws(()=>publishRecord(root,planned.record),/exists|sequence|chain|pending/);
  assert.equal(readLifecycle(root).report.status,"pending-write");
  writeFileSync(join(root,"main.sot.json"),JSON.stringify(planned.record.after[0].sot));
  assert.equal(readLifecycle(root).report.status,"pending-write","mixed before/after state must remain incomplete");
  const external=structuredClone(docs[1].sot);external.title="Unrecorded human edit";
  writeFileSync(join(root,"initiatives","batch.sot.json"),JSON.stringify(external));
  assert.equal(readLifecycle(root).report.status,"external-drift");
  assert.throws(()=>runLifecycle(root,{kind:"recover"},{apply:true}),/drift/);
  assert.throws(()=>runLifecycle(root,{kind:"capture",reason:"Hide an incomplete transaction"},{apply:true}),/pending/);
  assert.equal(JSON.parse(readFileSync(join(root,"initiatives","batch.sot.json"),"utf8")).title,"Unrecorded human edit");
  writeFileSync(join(root,"initiatives","batch.sot.json"),JSON.stringify(docs[1].sot));
  assert.equal(runLifecycle(root,{kind:"recover"},{apply:true}).status,"current");
  assert.equal(runLifecycle(root,{kind:"recover"},{apply:true}).status,"current","recovery is idempotent");
  assert.equal(readLifecycle(root).records.length,2);
  assert.ok(readLifecycle(root).report.pendingReviews.some(r=>r.type==="merge-prd"));
  assert.equal(readLifecycle(root).report.productApproval,"not-assessed");
  console.log("[journal-store] PASS dry-run, immutable intent, mixed-write recovery and unknown-content protection");

  const reverted=setup("reverted");
  runLifecycle(reverted,{kind:"init",reason:"Enroll"},{apply:true});
  const beforeRevert=readFileSync(join(reverted,"main.sot.json"),"utf8");
  runLifecycle(reverted,{kind:"merge",initiative:"batch",reason:"Complete merge"},{apply:true});
  writeFileSync(join(reverted,"main.sot.json"),beforeRevert);
  assert.equal(readLifecycle(reverted).report.status,"external-drift","a completed transaction's external revert is not an interrupted write");
  assert.throws(()=>runLifecycle(reverted,{kind:"recover"},{apply:true}),/drift/);
  assert.equal(readFileSync(join(reverted,"main.sot.json"),"utf8"),beforeRevert);
  assert.equal(runLifecycle(reverted,{kind:"capture",reason:"Acknowledge explicit external revert"},{apply:true}).status,"current");

  withLifecycleLock(root,()=>assert.throws(()=>runLifecycle(root,{kind:"capture",reason:"Concurrent"},{apply:true}),/locked/));
  const lock=join(root,"history","lifecycle","write.lock");mkdirSync(lock);
  writeFileSync(join(lock,"owner.json"),JSON.stringify({pid:process.pid,host:hostname()}));
  assert.throws(()=>runLifecycle(root,{kind:"unlock"},{apply:true}),/running/);
  const child=spawnSync(process.execPath,["-e",""],{encoding:"utf8"});
  writeFileSync(join(lock,"owner.json"),JSON.stringify({pid:child.pid,host:"a-different-host"}));
  assert.throws(()=>runLifecycle(root,{kind:"unlock"},{apply:true}),/foreign/);
  writeFileSync(join(lock,"owner.json"),JSON.stringify({pid:child.pid,host:hostname()}));
  assert.equal(runLifecycle(root,{kind:"unlock"},{apply:true}).status,"unlocked");
  assert.equal(existsSync(lock),false);
  const history=join(root,"history","lifecycle","records");
  const head=join(history,readdirSync(history).filter(f=>f.endsWith(".json")).sort()[1]);
  const preserved=readFileSync(head,"utf8");writeFileSync(head,preserved.replace("Land batch","tampered"));
  assert.throws(()=>readLifecycle(root),/digest/);
  writeFileSync(head,preserved);
  const heldTail=join(temp,"held-tail.json");renameSync(head,heldTail);
  assert.throws(()=>runLifecycle(root,{kind:"capture",reason:"Do not recreate a lost tail"},{apply:true}),/journal|history/);
  assert.equal(existsSync(head),false,"missing history must not be replaced by a new record with the same sequence");
  renameSync(heldTail,head);
  renameSync(history,history+".held");
  assert.throws(()=>readLifecycle(root),/history|journal|record/);
  assert.throws(()=>runLifecycle(root,{kind:"init",reason:"Do not replace lost history"},{apply:true}),/history|journal|record/);
  renameSync(history+".held",history);
  console.log("[journal-store] PASS exclusive writers, verified dead-lock release and hash drift rejection");

  const cli=fileURLToPath(new URL("../scripts/lifecycle.mjs",import.meta.url));
  const result=spawnSync(process.execPath,[cli,root,"status","--json","--id","root/F1"],{encoding:"utf8"});
  assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).lookup.active,true);
  for(const args of [[root,"status","--apply"],[root,"approve"],[root,"apply","--plan"],[root,"status","--unknown"]]) {
    assert.notEqual(spawnSync(process.execPath,[cli,...args],{encoding:"utf8"}).status,0);
  }
  const fresh=setup("fresh");
  const preview=spawnSync(process.execPath,[cli,fresh,"init","--reason","Initial capture","--json"],{encoding:"utf8"});
  assert.equal(preview.status,0,preview.stderr);assert.equal(existsSync(join(fresh,"history")),false);
  const escaped=setup("escaped"),outside=join(temp,"outside");mkdirSync(outside);
  symlinkSync(outside,join(escaped,"history"),"junction");
  assert.throws(()=>runLifecycle(escaped,{kind:"init",reason:"Reject redirected history"},{apply:true}),/symlink/);
  assert.deepEqual(readdirSync(outside),[],"history writes must not follow a junction outside the workspace");
  const bundle=packagePlugin(join(temp,"vibespec"));
  const packaged=spawnSync(process.execPath,[join(bundle,"skills","vibespec","scripts","lifecycle.mjs"),fresh,"init","--reason","Packaged runtime test","--apply","--json"],{encoding:"utf8"});
  assert.equal(packaged.status,0,packaged.stderr);
  assert.equal(JSON.parse(packaged.stdout).status,"current");
  assert.equal(readLifecycle(fresh).records.length,1);
  console.log("[journal-cli] PASS read-only lookup, explicit mutation and malformed-argument rejection");
} finally { rmSync(temp,{recursive:true,force:true}); }
